name: pinger
description: Ping command utility app made with Flutter.

version: 1.1.4+9

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  cloud_firestore: ^4.9.1
  connectivity: ^3.0.6
  dotted_border: ^2.0.0+3
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_vibrate: ^1.3.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  http: ^1.1.0
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  location: ^5.0.3
  mobx: ^2.2.0
  package_info: ^2.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  import_sorter: ^4.6.0
  intl_utils: ^2.8.4
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mobx_codegen: ^2.3.0
  mockito: ^5.4.2
  r_flutter: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/

flutter_intl:
  enabled: true
