name: pinger
description: Ping command utility app made with Flutter.

version: 1.1.4+9

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.9
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  dotted_border: ^2.0.0+1
  freezed_annotation: ^1.0.0
  injectable: ^1.5.0
  get_it: ^7.2.0
  intl: ^0.17.0
  path_provider: ^2.0.7
  location: ^4.3.0
  flutter_local_notifications: ^9.1.4
  http: ^0.13.4
  cloud_firestore: ^3.1.0
  firebase_crashlytics: ^2.3.0
  google_fonts: ^2.1.0
  fl_chart: ^0.40.2
  package_info: ^2.0.2
  connectivity: ^3.0.6
  app_settings: ^4.1.1
  permission_handler: ^8.3.0
  flutter_vibrate : ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.4
  json_serializable: ^6.0.1
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  r_flutter: ^0.9.0
  mockito: ^5.0.16

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/

flutter_intl:
  enabled: true
