name: pinger
description: Ping command utility app made with Flutter.

version: 1.1.4+9

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  app_settings: ^4.1.1
  cloud_firestore: ^3.1.0
  connectivity: ^3.0.6
  dotted_border: ^2.0.0+1
  firebase_crashlytics: ^2.3.0
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.4
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.2
  flutter_vibrate: ^1.3.0
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  location: ^4.3.0
  mobx: ^2.0.5
  package_info: ^2.0.2
  path_provider: ^2.0.7
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  import_sorter: ^4.6.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  mobx_codegen: ^2.0.4
  mockito: ^5.0.16
  r_flutter: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/

flutter_intl:
  enabled: true
