name: pinger
description: Ping command utility app made with Flutter.

version: 1.1.7+12

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  cloud_firestore: ^4.13.6
  connectivity: ^3.0.6
  dotted_border: ^2.1.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.2.0+1
  flutter_vibrate: ^1.3.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http: ^1.1.2
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  location: ^5.0.3
  mobx: ^2.2.3
  package_info: ^2.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  import_sorter: ^4.6.0
  intl_utils: ^2.8.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mobx_codegen: ^2.4.0
  mockito: ^5.4.3
  r_flutter: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/

flutter_intl:
  enabled: true
