source "https://rubygems.org"

# https://github.com/fastlane/fastlane/issues/16621
gem "fastlane", ">= 2.150.0.rc3"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
