default_platform(:ios)

appId = ENV['APP_ID']

platform :ios do
    lane :setup_code_signing do
        create_keychain(
            name: ENV['KEYCHAIN_NAME'],
            password: ENV['KEYCHAIN_PASSWORD'],
            timeout: false,
            unlock: true,
        )

        match(
            git_url: ENV['GIT_URL'],
            git_basic_authorization: ENV['GIT_BASIC_AUTHORIZATION'],
            keychain_name: ENV['KEYCHAIN_NAME'],
            keychain_password: ENV['KEYCHAIN_PASSWORD'],
            type: "adhoc",
            app_identifier: appId,
            readonly: true,
        )
        
        update_project_provisioning(
            xcodeproj: "Runner.xcodeproj",
            target_filter: "Runner",
            build_configuration: "Release",
            profile: ENV['sigh_#{appId}_adhoc_profile-path'],
            code_signing_identity: ENV['IOS_SIGNING_IDENTITY'],
        )

        update_code_signing_settings(
            use_automatic_signing: false,
            path: "Runner.xcodeproj",
        )
    end

    lane :build_and_publish_firebase do
        build_app(
            workspace: "Runner.xcworkspace",
            scheme: ENV['APP_FLAVOR'],
            export_method: "ad-hoc",
            output_name: "Runner.ipa",
            export_options: {
                provisioningProfiles: {
                    appId => ENV['sigh_#{appId}_adhoc_profile-name']
                }
            },
        )

        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            groups: ENV['FIREBASE_GROUPS'],
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
        )
    end
end
