default_platform(:android)

flavor = ENV["APP_FLAVOR"]

platform :android do
    lane :publish_firebase do
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            groups: ENV["FIREBASE_GROUPS"],
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            apk_path: "../build/app/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk",
        )
    end

    lane :publish_play_store do
        upload_to_play_store(
            json_key_data: ENV["JSON_KEY_DATA"],
            package_name: ENV["PACKAGE_NAME"],
            aab: "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
        )
    end
end
