default_platform(:android)

flavor = ENV['APP_FLAVOR']

platform :android do
    lane :publish do
        firebase_app_distribution(
            app: ENV['FIREBASE_APP_ID'],
            groups: ENV['FIREBASE_GROUPS'],
            firebase_cli_token: ENV['FIREBASE_TOKEN'],
            apk_path: "../build/app/outputs/apk/#{flavor]}/release/app-#{flavor}-release.apk",
        )
    end
end
