name: internal_android

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_and_publish_android_to_firebase:
    name: Publish Android app for internal testing
    runs-on: macOS-latest
    env:
      APP_ID: com.tomwyr.pinger.dev
      APP_FLAVOR: dev
      FIREBASE_GROUPS: testers
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: npm install -g firebase-tools
      - run: flutter pub get
      - name: Decode confidential files
        env:
          FIREBASE_API_KEY_ANDROID: ${{secrets.FIREBASE_API_KEY_ANDROID_DEV}}
        run: echo $FIREBASE_API_KEY_ANDROID | base64 -d > android/app/src/dev/google-services.json
      # Build and publish Android
      - name: Build Android
        run: flutter build apk --flavor dev
      - name: Publish Android
        working-directory: ./android
        env:
          FIREBASE_APP_ID: 1:19662603391:android:d82f1b46633823fabd2b4a
        run: fastlane publish_firebase
