name: internal_ios

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_and_publish_ios_to_firebase:
    name: Publish iOS app for internal testing
    runs-on: macOS-latest
    env:
      APP_ID: com.tomwyr.pinger.dev
      APP_FLAVOR: dev
      FIREBASE_GROUPS: testers
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: npm install -g firebase-tools
      - run: flutter pub get
      - name: Decode confidential files
        env:
          FIREBASE_API_KEY_IOS: ${{secrets.FIREBASE_API_KEY_IOS_DEV}}
        run: mkdir -p ios/Config/dev && echo $FIREBASE_API_KEY_IOS | base64 -d > ios/Config/dev/GoogleService-Info.plist
      # Build and publish iOS
      - name: Build iOS
        run: flutter build ios --flavor dev --no-codesign
      - name: Archive iOS
        working-directory: ./ios
        env:
          GIT_URL: https://github.com/tomwyr/pinger-ios-signing.git
          KEYCHAIN_NAME: pinger-keychain
          KEYCHAIN_PASSWORD: ${{secrets.KEYCHAIN_PASSWORD}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          GIT_BASIC_AUTHORIZATION: ${{secrets.GIT_BASIC_AUTHORIZATION}}
          IOS_SIGNING_IDENTITY: ${{secrets.IOS_SIGNING_IDENTITY}}
          PROFILE_TYPE: adhoc
          EXPORT_METHOD: ad-hoc
        run: fastlane sign_and_build_app
      - name: Publish iOS
        working-directory: ./ios
        env:
          FIREBASE_APP_ID: 1:19662603391:ios:ebe2f5ff1246910bbd2b4a
        run: fastlane publish_firebase
